apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  labels:
    app: my-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: australia-southeast1-docker.pkg.dev/sit323-24t1-janghu-05d700b/my-repo/my-node-app:latest
        ports:
        - containerPort: 3000
